02 file added

diff --git a/09-install-MYSQL b/09-install-MYSQL
--- a/09-install-MYSQL
+++ b/09-install-MYSQL
@@ -12,4 +12,12 @@ fi
 
 yum install mysql -y
 
+if [ $? is -ne 0]
+then 
+    echo "ERROR:: Installation of MYDQL is failed"
+    exit 1
+else
+    echo "Installation of MYSQK is success"
+fi
+
 
